# Generated by Django 3.2 on 2022-03-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20220307_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_before_vat',
            new_name='vat',
        ),
    ]
