# Generated by Django 3.2 on 2022-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_previousproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('github_link', models.URLField(blank=True, max_length=254, null=True)),
                ('facebook_link', models.URLField(blank=True, max_length=254, null=True)),
                ('linkedin_link', models.URLField(blank=True, max_length=254, null=True)),
                ('twitter_link', models.URLField(blank=True, max_length=254, null=True)),
                ('about_entry_one', models.CharField(blank=True, max_length=254, null=True)),
                ('about_entry_two', models.CharField(blank=True, max_length=254, null=True)),
                ('about_entry_three', models.CharField(blank=True, max_length=254, null=True)),
                ('hero_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('about_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
