# Generated by Django 3.2 on 2022-03-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
