# Generated by Django 3.2 on 2022-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220308_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='about_entry_one',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='about_entry_three',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuser',
            name='about_entry_two',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
