# Generated by Django 3.2 on 2022-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220309_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuser',
            name='about_entry_one',
            field=models.TextField(max_length=254),
        ),
    ]
