# Generated by Django 3.2 on 2022-03-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aboutuser_about_entry_one'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreviousProject',
        ),
        migrations.AlterModelOptions(
            name='aboutuser',
            options={'verbose_name_plural': 'About the user'},
        ),
    ]
