# Generated by Django 3.2 on 2022-03-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220310_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
